services:
  nuxt:
    image: ${CI_REGISTRY_IMAGE}:staging
    restart: always
    environment:
      NODE_ENV: staging
      MONGO_URL: mongodb://mongo:27017/mydb_staging
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_staging:/data/db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuxt

volumes:
  mongo_staging:
